apiVersion: v1
kind: Namespace
metadata:
 name: datadog
 labels:
   name              = "datadog"
   xkf.xenit.io/kind = "platform"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 1m0s
  url: "https://helm.datadoghq.com"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog-operator
  namespace: datadog
spec:
  chart:
    spec:
      chart: datadog-operator
      sourceRef:
        kind: HelmRepository
        name: datadog
      version: 1.0.2
  values:
    apiKeyExistingSecret: datadog-operator-apikey
    appKeyExistingSecret: datadog-operator-appkey
    installCRDs: true
    image:
      tag: 1.0.2
    datadogMonitor:
      enabled: true
    resources:
      requests:
        cpu: 15m
        memory: 50Mi
  interval: 1m0s
