{{- if .Values.servicemonitor.loadBalancer }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "azure-metrics-exporter.labels" . | nindent 4 }}
    xkf.xenit.io/monitoring: platform
  name: {{ include "azure-metrics-exporter.fullname" . }}-loadbalancers
spec:
  endpoints:
  - interval: 60s
    port: http
    path: /probe/metrics/list
    params:
      name: ["azure-metric"]
      subscription:
        - {{ .Values.subscription }}
      template:
        - '{name}_{metric}_{aggregation}_{unit}'
      resourceType:
        - Microsoft.Network/loadBalancers
      aggregation:
        - average
        - total
      metric:
        - SnatConnectionCount
        - AllocatedSnatPorts
        - UsedSnatPorts
  selector:
    matchLabels:
      {{- include "azure-metrics-exporter.labels" . | nindent 6 }}
{{- end }}
---
{{- if .Values.servicemonitor.kubernetes }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "azure-metrics-exporter.labels" . | nindent 4 }}
    xkf.xenit.io/monitoring: platform
  name: {{ include "azure-metrics-exporter.fullname" . }}-kubernetes
spec:
  endpoints:
  - interval: 60s
    port: http
    path: /probe/metrics/list
    params:
      name: ["azure-metric"]
      subscription:
        - {{ .Values.subscription }}
      template:
        - '{metric}'
      resourceType:
        - Microsoft.ContainerService/managedClusters
      aggregation:
        - average
        - total
      metric:
        - cluster_autoscaler_cluster_safe_to_autoscale
        - cluster_autoscaler_scale_down_in_cooldown
        - cluster_autoscaler_unneeded_nodes_count
        - cluster_autoscaler_unschedulable_pods_count
  selector:
    matchLabels:
      {{- include "azure-metrics-exporter.labels" . | nindent 6 }}
{{- end }}
