environment: dev
clusterName: aks1
credentialsSecretName: grafana-agent-credentials

remote:
  metricsUrl: ""
  logsUrl: ""
  tracesUrl: ""

# The resource values specified for agent will apply both to grafana-agent and grafana-agent-logs
# since it is not possible to configure different values for those two
agent:
  resources:
    requests:
      cpu: 25m
      memory: 100Mi

traces:
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
