nameOverride: ""
fullnameOverride: ""
notificationEmail: ""
acmeServer: ""

cloudProvider: ""

azureConfig:
  resourceGroupName: ""
  clientID: ""
  subscriptionID: ""
  hostedZoneName: []
  resourceID: ""

awsConfig:
  region: ""
  zones:
    - hostedZoneID: ""
      name: ""
